source 'https://github.com/CocoaPods/Specs.git'
platform :ios,			'7.0'
inhibit_all_warnings!

target:'MengNavigation'

pod 'Masonry', '1.1.0'

#pod 'SDWebImage'
pod 'SDWebImage', '~> 3.8.1'
#pod 'SDWebImage/WebP'

pod 'YYWebImage'

